book_app/urls.py
from django.urls import path

from .views import (authors_list, author_edit, author_create, author_delete, student_book_detail, save_books,
                    student_book_list)

app_name = "book_app"

urlpatterns = [
    # Student
    path('', student_book_list, name='student_book_list'),
    path('<int:pk>/', student_book_detail, name='student_book_detail'),

    # Library Admin
    path('authors/list/', authors_list, name='authors_list'),

    path('authors/create/', author_create, name='author_create'),
    path('authors/edit/<int:author_id>/', author_edit, name='author_edit'),
    path('authors/delete/<int:author_id>/', author_delete, name='author_delete'),

    path('save-books/', save_books, name='save_books'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

# Static settings
from django.conf import settings
from django.conf.urls.static import static

# Admin custom
admin.site.site_title = "Admin"
admin.site.site_header = "XIU Library"
admin.site.index_title = "Dashboard"

urlpatterns = [
    path('admin/', admin.site.urls),

    # Hemis Oauth
    path('auth/', include('oauth.urls')),

    # Dashboard
    path('', include('dashboard_app.urls')),

    # Book
    path('books/', include('book_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_app/models.py
from django.db import models

from user_app.models import StudentProfile


class Author(models.Model):
    full_name = models.CharField(max_length=200, verbose_name="Ism Familiya")

    bio = models.TextField(verbose_name="Qisqacha tavsif", blank=True, null=True)

    class Meta:
        verbose_name = "Muallif"
        verbose_name_plural = "Mualliflar"

    def __str__(self):
        return self.full_name


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name="Katalog nomi")
    icon = models.TextField(verbose_name="Ikonkasi", null=True, blank=True)

    class Meta:
        verbose_name = "Katalog"
        verbose_name_plural = "Kataloglar"

    def __str__(self):
        return self.name

    def book_count(self):
        return self.book_set.all().count()


class Book(models.Model):
    title = models.CharField(max_length=500, verbose_name="Kitob nomi")

    authors = models.ManyToManyField(Author, verbose_name="Mualliflar")
    # genres = models.ManyToManyField(Genre, verbose_name="Kataloglar")
    category = models.ForeignKey(Genre, verbose_name="Katalog", on_delete=models.PROTECT)

    published_date = models.CharField(max_length=255, verbose_name="Chop etilgan sana", null=True, blank=True, default="2020")

    description = models.TextField(verbose_name="Qisqacha tavsif", blank=True, null=True)

    audio_version = models.FileField(upload_to="audio_books/", verbose_name="Audio versiyasi", blank=True, null=True)
    electronic_version = models.FileField(upload_to="ebooks/", verbose_name="Elektron versiyasi", blank=True, null=True)

    page_count = models.PositiveIntegerField(verbose_name="Sahifalar soni", blank=True, null=True)
    cover_image = models.ImageField(upload_to="book_covers/", verbose_name="Muqova rasmi", blank=True, null=True)

    language = models.CharField(max_length=50, verbose_name="Til", default="O'zbekcha")
    isbn = models.CharField(max_length=13, verbose_name="ISBN", blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Kitob yaratilgan sana")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Kitob yangilangan sana")

    class Meta:
        verbose_name = "Kitob"
        verbose_name_plural = "Kitoblar"
        ordering = ['-id']

    def __str__(self):
        return self.title

    def copy_count(self):
        """Faqat mavjud (`is_available=True`) bo'lgan kitob nusxalarini qaytaradi."""
        return self.copy_set.filter(is_available=True).count()


class Copy(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Kitob")
    inventory_number = models.CharField(max_length=50, verbose_name="Inventar raqami")
    is_available = models.BooleanField(default=True, verbose_name="Mavjudmi")

    class Meta:
        verbose_name = "Nusxa"
        verbose_name_plural = "Nusxalar"

    def __str__(self):
        return f"{self.book.title} - {self.inventory_number}"


class Rental(models.Model):
    copy = models.ForeignKey(Copy, on_delete=models.CASCADE, verbose_name="Nusxa")
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE, verbose_name="O'quvchi")

    library_admin_checked = models.BooleanField(default=False, verbose_name="Kutubxonachi tasdiqladimi?")

    borrowed_date = models.DateField(verbose_name="Olgan sana", blank=True, null=True)
    return_date = models.DateField(verbose_name="Qaytarish sanasi", blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Kitob yaratilgan sana")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Kitob yangilangan sana")

    class Meta:
        verbose_name = "Ijara"
        verbose_name_plural = "Ijaralar"

    def __str__(self):
        return f"{self.copy.book.title} ({self.student.user.first_name} {self.student.user.third_name})"

book_app/forms.py
from django import forms
from .models import Author, Genre, Book, Copy, Rental

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['full_name', 'bio']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ism Familiya'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Qisqacha tavsif', 'rows': 4}),
        }


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Janr nomi'}),
        }


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title', 'authors', 'category', 'published_date', 'description', 'audio_version',
            'electronic_version', 'page_count', 'cover_image', 'language', 'isbn'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Kitob nomi'}),
            'authors': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'published_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Qisqacha tavsif', 'rows': 4}),
            'audio_version': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'electronic_version': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'page_count': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Sahifalar soni'}),
            'cover_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'language': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Til'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ISBN'}),
        }


class CopyForm(forms.ModelForm):
    class Meta:
        model = Copy
        fields = ['book', 'inventory_number', 'is_available']
        widgets = {
            'book': forms.Select(attrs={'class': 'form-control'}),
            'inventory_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Inventar raqami'}),
            'is_available': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class RentalForm(forms.ModelForm):
    class Meta:
        model = Rental
        fields = ['copy', 'student', 'borrowed_date', 'return_date']
        widgets = {
            'copy': forms.Select(attrs={'class': 'form-control'}),
            'student': forms.Select(attrs={'class': 'form-control'}),
            'borrowed_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'return_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

book_app/views/author.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages

from user_app.utils import library_admin_role_required
from ..models import Author
from ..forms import AuthorForm


@library_admin_role_required
def authors_list(request):
    authors = Author.objects.all()

    create_form = AuthorForm(request.POST)

    success_message = request.GET.get('successMessage', '')

    ctx = {
        # Menu active
        'sidebarAdditional': True,
        'sidebarAdditionalAuthors': True,

        # Main
        'authors': authors,
        'create_form': create_form,
        'successMessage': success_message,  # successMessage ni contextga qo'shish
    }

    return render(request, 'book_app/author/list.html', ctx)


@library_admin_role_required
def author_create(request):
    if request.method == "POST":
        full_name = request.POST.get('full_name')
        bio = request.POST.get('bio')

        if full_name:
            # Muallifni qo'shish
            Author.objects.create(full_name=full_name, bio=bio)
            success_message = "Muallif muvaffaqiyatli qo'shildi."
            # URL parametrlarini qo'shish
            return redirect(reverse('book_app:authors_list') + f"?successMessage={success_message}")

        else:
            success_message = "Ism Familiya maydoni to'ldirilishi shart."
            return redirect(reverse('book_app:authors_list') + f"?successMessage={success_message}")

    return redirect('book_app:authors_list')

@library_admin_role_required
def author_edit(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == "POST":
        author.full_name = request.POST.get('full_name')
        author.bio = request.POST.get('bio')
        author.save()
        messages.success(request, "Muallif muvaffaqiyatli tahrirlandi.")
        return redirect('book_app:authors_list')

    return render(request, 'book_app/author/edit.html', {'author': author})


@library_admin_role_required
def author_delete(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == "POST":
        author.delete()
        messages.success(request, "Muallif muvaffaqiyatli o'chirildi.")
        return redirect('book_app:authors_list')

    return render(request, 'book_app/author/delete.html', {'author': author})

book_app/views/book.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
from django.db.models import Q

from ..utils import is_book_borrowed_by_student

from ..models import Book, Genre

def is_student(user):
    return user.is_authenticated and user.user_type == "STUDENT"

@login_required
def student_book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)

    book_rental = is_book_borrowed_by_student(request.user.student_profile, book)

    context = {
        'book': book,
        'book_rental': book_rental
    }
    return render(request, "book_app/book/detail.html", context)


@login_required
def student_book_list(request):
    query = request.GET.get('q', '')
    category_id = request.GET.get('category', '')
    language = request.GET.get('language', '')

    books = Book.objects.select_related('category').prefetch_related('authors').all()

    if query:
        books = books.filter(Q(title__icontains=query) | Q(authors__full_name__icontains=query)).distinct()

    if category_id:
        books = books.filter(category_id=category_id)

    # if language:
    #     books = books.filter(language=language)

    categories = Genre.objects.all()

    page_number = request.GET.get('page', 1)
    paginator = Paginator(books, 12)
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'query': query,
        'category_id': category_id,
        'language': language,
        'categories': categories,
    }
    return render(request, "book_app/book/book_list.html", context)

book_app/views/save_books.py
import requests
import random

from django.core.files import File
from io import BytesIO
import os

from django.http import JsonResponse
from django.shortcuts import render

from ..models import Book, Author, Genre
from user_app.utils import library_admin_role_required


@library_admin_role_required
def save_books(request):
    if request.method == "POST":
        url = request.POST.get("url")
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()
            books = data.get("results", [])

            for book in books:

                book_data = {
                    'title': book.get('title', '.'),
                    'author': book.get('author', {}).get('name', '.'),
                    'category': book.get('category', {}).get('title', 'Boshqa'),
                    'published_date': str(book.get('year')),  # Use the parse_date function
                    'description': book.get('description', '.'),
                    'electronic_version': book.get('source', '.'),
                    'page_count': random.randint(200, 400),
                    'cover_image': book.get('photo', ''),
                    'language': "O'zbekcha",
                    'isbn': "",
                }

                author, created = Author.objects.get_or_create(full_name=book_data['author'])
                category, created = Genre.objects.get_or_create(name=book_data['category'])

                # Create the book instance
                book_create = Book(
                    title=book_data['title'],
                    published_date=book_data['published_date'],
                    description=book_data['description'],
                    page_count=book_data['page_count'],
                    language=book_data['language'],
                    isbn=book_data['isbn'],
                    category=category,  # Assign the category directly here
                )

                # Save the book instance to generate a primary key (ID)
                book_create.save()

                # Now you can add the author to the many-to-many field
                book_create.authors.add(author)

                # Handle book cover image
                image_url = book_data['cover_image']
                if image_url:
                    image_response = requests.get(image_url)
                    if image_response.status_code == 200:
                        img_temp = BytesIO(image_response.content)
                        book_create.cover_image.save(os.path.basename(image_url), File(img_temp))

                # Handle electronic version
                book_url = book_data['electronic_version']
                if book_url:
                    book_response = requests.get(book_url)
                    if book_response.status_code == 200:
                        book_temp = BytesIO(book_response.content)
                        book_create.electronic_version.save(os.path.basename(book_url), File(book_temp))

            return JsonResponse({
                "success": f"{len(books)} ta kitob muvaffaqqiyatli qo'shildi!"
            })


        else:
            return JsonResponse({"error": f"Xatolik yuz berdi: {response.status_code}"}, status=400)

    return render(request, 'custom/save_books.html')

templates/book_app/author/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h4 class="mb-3">Muallif qo'shish</h4>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="full_name">Ism Familiya</label>
                    <input type="text" name="full_name" id="full_name" class="form-control" required>
                </div>
                <div class="form-group mt-3">
                    <label for="bio">Muallif haqida</label>
                    <textarea name="bio" id="bio" class="form-control"></textarea>
                </div>
                <div class="form-group mt-4">
                    <button type="submit" class="btn btn-success">Saqlash</button>
                    <a href="{% url 'book_app:authors_list' %}" class="btn btn-secondary">Bekor qilish</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/book_app/author/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h4 class="mb-3">Muallifni o'chirish</h4>
            <p>Haqiqatan ham "{{ author.full_name }}" ni o'chirishni xohlaysizmi?</p>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Ha, o'chirish</button>
                <a href="{% url 'book_app:authors_list' %}" class="btn btn-secondary">Bekor qilish</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/book_app/author/list.html
{% extends 'base.html' %}
{% load static %}

{% block sidebar %}
{% include 'sidebar/library_admin.html' %}
{% endblock sidebar %}

{% block topbar_header %}
{% include 'topbar_header/library_admin.html' %}
{% endblock topbar_header %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0">Mualliflar</h4>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card" id="customerList">
                <div class="card-header border-bottom-dashed">

                    <div class="row g-4 align-items-center">
                        <div class="col-sm">
                            <div>
                                <h5 class="card-title mb-0">Mualliflar</h5>
                            </div>
                        </div>
                        <div class="col-sm-auto">
                            <div class="d-flex flex-wrap align-items-start gap-2">
                                <button class="btn btn-soft-danger" id="remove-actions" onclick="deleteMultiple()"><i
                                        class="ri-delete-bin-2-line"></i></button>
                                <button type="button" class="btn btn-primary add-btn" data-bs-toggle="modal"
                                        id="create-btn" data-bs-target="#showModal"><i
                                        class="ri-add-line align-bottom me-1"></i> Muallif qo'shish
                                </button>
                                <button type="button" class="btn btn-secondary"><i
                                        class="ri-file-download-line align-bottom me-1"></i> Excel yukab olish
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body border-bottom-dashed border-bottom">
                    <form>
                        <div class="row g-3 align-items-center">
                            <!-- Search Box -->
                            <div class="col-lg-9 col-md-9 col-sm-12">
                                <div class="search-box">
                                    <input type="text" class="form-control search"
                                           placeholder="Qidiruv uchun ism yoki familiya kiriting...">
                                    <i class="ri-search-line search-icon"></i>
                                </div>
                            </div>

                            <!-- Filters Button -->
                            <div class="col-lg-3 col-md-3 col-sm-12">
                                <div>
                                    <button type="button" class="btn btn-primary w-100" onclick="SearchData();">
                                        <i class="ri-equalizer-fill me-2 align-bottom"></i> Filterlash
                                    </button>
                                </div>
                            </div>
                        </div>

                        <!--end row-->
                    </form>
                </div>
                <div class="card-body">
                    <div>
                        <div class="table-responsive table-card mb-1">
                            <table class="table align-middle" id="customerTable">
                                <thead class="table-light text-muted">
                                <tr>
                                    <th scope="col" style="width: 50px;">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="checkAll"
                                                   value="option">
                                        </div>
                                    </th>

                                    <th class="sort" data-sort="customer_name">Customer</th>
                                    <th class="sort" data-sort="email">Email</th>
                                    <th class="sort" data-sort="phone">Phone</th>
                                    <th class="sort" data-sort="date">Joining Date</th>
                                    <th class="sort" data-sort="status">Status</th>
                                    <th class="sort" data-sort="action">Action</th>
                                </tr>
                                </thead>
                                <tbody class="list form-check-all">
                                <tr>
                                    <th scope="row">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="chk_child"
                                                   value="option1">
                                        </div>
                                    </th>
                                    <td class="id" style="display:none;"><a href="javascript:void(0);"
                                                                            class="fw-medium link-primary">#VZ2101</a>
                                    </td>
                                    <td class="customer_name">Mary Cousar</td>
                                    <td class="email">marycousar@velzon.com</td>
                                    <td class="phone">580-464-4694</td>
                                    <td class="date">06 Apr, 2021</td>
                                    <td class="status"><span
                                            class="badge bg-success-subtle text-success text-uppercase">Active</span>
                                    </td>
                                    <td>
                                        <ul class="list-inline hstack gap-2 mb-0">
                                            <li class="list-inline-item edit" data-bs-toggle="tooltip"
                                                data-bs-trigger="hover" data-bs-placement="top" aria-label="Edit"
                                                data-bs-original-title="Edit">
                                                <a href="#showModal" data-bs-toggle="modal"
                                                   class="text-primary d-inline-block edit-item-btn">
                                                    <i class="ri-pencil-fill fs-16"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item" data-bs-toggle="tooltip"
                                                data-bs-trigger="hover" data-bs-placement="top" aria-label="Remove"
                                                data-bs-original-title="Remove">
                                                <a class="text-danger d-inline-block remove-item-btn"
                                                   data-bs-toggle="modal" href="#deleteRecordModal">
                                                    <i class="ri-delete-bin-5-fill fs-16"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <div class="noresult" style="display: none">
                                <div class="text-center">
                                    <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop"
                                               colors="primary:#121331,secondary:#08a88a"
                                               style="width:75px;height:75px">
                                    </lord-icon>
                                    <h5 class="mt-2">Sorry! No Result Found</h5>
                                    <p class="text-muted mb-0">We've searched more than 150+ Customers
                                        We did not find any
                                        Customers for you search.</p>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end">
                            <div class="pagination-wrap hstack gap-2">
                                <a class="page-item pagination-prev disabled" href="#">
                                    Previous
                                </a>
                                <ul class="pagination listjs-pagination mb-0">
                                    <li class="active"><a class="page" href="#" data-i="1" data-page="8">1</a></li>
                                </ul>
                                <a class="page-item pagination-next" href="#">
                                    Next
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="showModal" tabindex="-1" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header bg-light p-3">
                                    <h5 class="modal-title" id="exampleModalLabel">Muallif qo'shish</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                                            id="close-modal"></button>
                                </div>
                                <form class="tablelist-form" method="post" action="{% url 'book_app:author_create' %}" autocomplete="off">
                                    {% csrf_token %}

                                    <div class="modal-body">
                    <div class="mb-3">
                        {{ create_form.full_name.label_tag }}
                        {{ create_form.full_name }}
                        {% if create_form.full_name.errors %}
                            <div class="invalid-feedback d-block">
                                {{ create_form.full_name.errors }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ create_form.bio.label_tag }}
                        {{ create_form.bio }}
                        {% if create_form.bio.errors %}
                            <div class="invalid-feedback d-block">
                                {{ create_form.bio.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Yopish</button>
                    <button type="submit" class="btn btn-success">Saqlash</button>
                </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Modal -->
                    <div class="modal fade zoomIn" id="deleteRecordModal" tabindex="-1" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="btn-close" id="deleteRecord-close"
                                            data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="mt-2 text-center">
                                        <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop"
                                                   colors="primary:#f7b84b,secondary:#f06548"
                                                   style="width:100px;height:100px"></lord-icon>
                                        <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
                                            <h4>Are you sure ?</h4>
                                            <p class="text-muted mx-4 mb-0">Are you sure you want to
                                                remove this record ?</p>
                                        </div>
                                    </div>
                                    <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
                                        <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Close
                                        </button>
                                        <button type="button" class="btn w-sm btn-danger " id="delete-record">Yes,
                                            Delete It!
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end modal -->
                </div>
            </div>

        </div>
        <!--end col-->
    </div>
</div>
{% endblock content %}