book_app/urls.py
from django.urls import path

from .views import (authors_list, author_edit, author_create, author_delete, student_book_detail, save_books,
                    student_book_list)

app_name = "book_app"

urlpatterns = [
    # Student
    path('', student_book_list, name='student_book_list'),
    path('<int:pk>/', student_book_detail, name='student_book_detail'),

    # Library Admin
    path('authors/list/', authors_list, name='authors_list'),

    path('authors/create/', author_create, name='author_create'),
    path('authors/edit/<int:author_id>/', author_edit, name='author_edit'),
    path('authors/delete/<int:author_id>/', author_delete, name='author_delete'),

    path('save-books/', save_books, name='save_books'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

# Static settings
from django.conf import settings
from django.conf.urls.static import static

# Admin custom
admin.site.site_title = "Admin"
admin.site.site_header = "XIU Library"
admin.site.index_title = "Dashboard"

urlpatterns = [
    path('admin/', admin.site.urls),

    # Hemis Oauth
    path('auth/', include('oauth.urls')),

    # Dashboard
    path('', include('dashboard_app.urls')),

    # Book
    path('books/', include('book_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_app/models.py
from django.db import models

from user_app.models import StudentProfile


class Author(models.Model):
    full_name = models.CharField(max_length=200, verbose_name="Ism Familiya")

    bio = models.TextField(verbose_name="Qisqacha tavsif", blank=True, null=True)

    class Meta:
        verbose_name = "Muallif"
        verbose_name_plural = "Mualliflar"

    def __str__(self):
        return self.full_name


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name="Katalog nomi")
    icon = models.TextField(verbose_name="Ikonkasi", null=True, blank=True)

    class Meta:
        verbose_name = "Katalog"
        verbose_name_plural = "Kataloglar"

    def __str__(self):
        return self.name

    def book_count(self):
        return self.book_set.all().count()


class Book(models.Model):
    title = models.CharField(max_length=500, verbose_name="Kitob nomi")

    authors = models.ManyToManyField(Author, verbose_name="Mualliflar")
    # genres = models.ManyToManyField(Genre, verbose_name="Kataloglar")
    category = models.ForeignKey(Genre, verbose_name="Katalog", on_delete=models.PROTECT)

    published_date = models.CharField(max_length=255, verbose_name="Chop etilgan sana", null=True, blank=True, default="2020")

    description = models.TextField(verbose_name="Qisqacha tavsif", blank=True, null=True)

    audio_version = models.FileField(upload_to="audio_books/", verbose_name="Audio versiyasi", blank=True, null=True)
    electronic_version = models.FileField(upload_to="ebooks/", verbose_name="Elektron versiyasi", blank=True, null=True)

    page_count = models.PositiveIntegerField(verbose_name="Sahifalar soni", blank=True, null=True)
    cover_image = models.ImageField(upload_to="book_covers/", verbose_name="Muqova rasmi", blank=True, null=True)

    language = models.CharField(max_length=50, verbose_name="Til", default="O'zbekcha")
    isbn = models.CharField(max_length=13, verbose_name="ISBN", blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Kitob yaratilgan sana")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Kitob yangilangan sana")

    class Meta:
        verbose_name = "Kitob"
        verbose_name_plural = "Kitoblar"
        ordering = ['-id']

    def __str__(self):
        return self.title

    def copy_count(self):
        """Faqat mavjud (`is_available=True`) bo'lgan kitob nusxalarini qaytaradi."""
        return self.copy_set.filter(is_available=True).count()


class Copy(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Kitob")
    inventory_number = models.CharField(max_length=50, verbose_name="Inventar raqami")
    is_available = models.BooleanField(default=True, verbose_name="Mavjudmi")

    class Meta:
        verbose_name = "Nusxa"
        verbose_name_plural = "Nusxalar"

    def __str__(self):
        return f"{self.book.title} - {self.inventory_number}"


class Rental(models.Model):
    copy = models.ForeignKey(Copy, on_delete=models.CASCADE, verbose_name="Nusxa")
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE, verbose_name="O'quvchi")

    library_admin_checked = models.BooleanField(default=False, verbose_name="Kutubxonachi tasdiqladimi?")

    borrowed_date = models.DateField(verbose_name="Olgan sana", blank=True, null=True)
    return_date = models.DateField(verbose_name="Qaytarish sanasi", blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Kitob yaratilgan sana")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Kitob yangilangan sana")

    class Meta:
        verbose_name = "Ijara"
        verbose_name_plural = "Ijaralar"

    def __str__(self):
        return f"{self.copy.book.title} ({self.student.user.first_name} {self.student.user.third_name})"

book_app/forms.py
from django import forms
from .models import Author, Genre, Book, Copy, Rental

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['full_name', 'bio']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ism Familiya'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Qisqacha tavsif', 'rows': 4}),
        }


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Janr nomi'}),
        }


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title', 'authors', 'category', 'published_date', 'description', 'audio_version',
            'electronic_version', 'page_count', 'cover_image', 'language', 'isbn'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Kitob nomi'}),
            'authors': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'published_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Qisqacha tavsif', 'rows': 4}),
            'audio_version': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'electronic_version': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'page_count': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Sahifalar soni'}),
            'cover_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'language': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Til'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ISBN'}),
        }


class CopyForm(forms.ModelForm):
    class Meta:
        model = Copy
        fields = ['book', 'inventory_number', 'is_available']
        widgets = {
            'book': forms.Select(attrs={'class': 'form-control'}),
            'inventory_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Inventar raqami'}),
            'is_available': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class RentalForm(forms.ModelForm):
    class Meta:
        model = Rental
        fields = ['copy', 'student', 'borrowed_date', 'return_date']
        widgets = {
            'copy': forms.Select(attrs={'class': 'form-control'}),
            'student': forms.Select(attrs={'class': 'form-control'}),
            'borrowed_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'return_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

book_app/views/author.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages

from user_app.utils import library_admin_role_required
from ..models import Author
from ..forms import AuthorForm


@library_admin_role_required
def authors_list(request):
    authors = Author.objects.all()

    create_form = AuthorForm(request.POST)

    success_message = request.GET.get('successMessage', '')

    ctx = {
        # Menu active
        'sidebarAdditional': True,
        'sidebarAdditionalAuthors': True,

        # Main
        'authors': authors,
        'create_form': create_form,
        'successMessage': success_message,  # successMessage ni contextga qo'shish
    }

    return render(request, 'book_app/author/list.html', ctx)


@library_admin_role_required
def author_create(request):
    if request.method == "POST":
        full_name = request.POST.get('full_name')
        bio = request.POST.get('bio')

        if full_name:
            # Muallifni qo'shish
            Author.objects.create(full_name=full_name, bio=bio)
            success_message = "Muallif muvaffaqiyatli qo'shildi."
            # URL parametrlarini qo'shish
            return redirect(reverse('book_app:authors_list') + f"?successMessage={success_message}")

        else:
            success_message = "Ism Familiya maydoni to'ldirilishi shart."
            return redirect(reverse('book_app:authors_list') + f"?successMessage={success_message}")

    return redirect('book_app:authors_list')

@library_admin_role_required
def author_edit(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == "POST":
        author.full_name = request.POST.get('full_name')
        author.bio = request.POST.get('bio')
        author.save()
        messages.success(request, "Muallif muvaffaqiyatli tahrirlandi.")
        return redirect('book_app:authors_list')

    return render(request, 'book_app/author/edit.html', {'author': author})


@library_admin_role_required
def author_delete(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == "POST":
        author.delete()
        messages.success(request, "Muallif muvaffaqiyatli o'chirildi.")
        return redirect('book_app:authors_list')

    return render(request, 'book_app/author/delete.html', {'author': author})

book_app/views/book.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
from django.db.models import Q

from ..utils import is_book_borrowed_by_student

from ..models import Book, Genre

def is_student(user):
    return user.is_authenticated and user.user_type == "STUDENT"

@login_required
def student_book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)

    book_rental = is_book_borrowed_by_student(request.user.student_profile, book)

    context = {
        'book': book,
        'book_rental': book_rental
    }
    return render(request, "book_app/book/detail.html", context)


@login_required
def student_book_list(request):
    query = request.GET.get('q', '')
    category_id = request.GET.get('category', '')
    language = request.GET.get('language', '')

    books = Book.objects.select_related('category').prefetch_related('authors').all()

    if query:
        books = books.filter(Q(title__icontains=query) | Q(authors__full_name__icontains=query)).distinct()

    if category_id:
        books = books.filter(category_id=category_id)

    # if language:
    #     books = books.filter(language=language)

    categories = Genre.objects.all()

    page_number = request.GET.get('page', 1)
    paginator = Paginator(books, 12)
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'query': query,
        'category_id': category_id,
        'language': language,
        'categories': categories,
    }
    return render(request, "book_app/book/book_list.html", context)

book_app/views/save_books.py
import requests
import random

from django.core.files import File
from io import BytesIO
import os

from django.http import JsonResponse
from django.shortcuts import render

from ..models import Book, Author, Genre
from user_app.utils import library_admin_role_required


@library_admin_role_required
def save_books(request):
    if request.method == "POST":
        url = request.POST.get("url")
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()
            books = data.get("results", [])

            for book in books:

                book_data = {
                    'title': book.get('title', '.'),
                    'author': book.get('author', {}).get('name', '.'),
                    'category': book.get('category', {}).get('title', 'Boshqa'),
                    'published_date': str(book.get('year')),  # Use the parse_date function
                    'description': book.get('description', '.'),
                    'electronic_version': book.get('source', '.'),
                    'page_count': random.randint(200, 400),
                    'cover_image': book.get('photo', ''),
                    'language': "O'zbekcha",
                    'isbn': "",
                }

                author, created = Author.objects.get_or_create(full_name=book_data['author'])
                category, created = Genre.objects.get_or_create(name=book_data['category'])

                # Create the book instance
                book_create = Book(
                    title=book_data['title'],
                    published_date=book_data['published_date'],
                    description=book_data['description'],
                    page_count=book_data['page_count'],
                    language=book_data['language'],
                    isbn=book_data['isbn'],
                    category=category,  # Assign the category directly here
                )

                # Save the book instance to generate a primary key (ID)
                book_create.save()

                # Now you can add the author to the many-to-many field
                book_create.authors.add(author)

                # Handle book cover image
                image_url = book_data['cover_image']
                if image_url:
                    image_response = requests.get(image_url)
                    if image_response.status_code == 200:
                        img_temp = BytesIO(image_response.content)
                        book_create.cover_image.save(os.path.basename(image_url), File(img_temp))

                # Handle electronic version
                book_url = book_data['electronic_version']
                if book_url:
                    book_response = requests.get(book_url)
                    if book_response.status_code == 200:
                        book_temp = BytesIO(book_response.content)
                        book_create.electronic_version.save(os.path.basename(book_url), File(book_temp))

            return JsonResponse({
                "success": f"{len(books)} ta kitob muvaffaqqiyatli qo'shildi!"
            })


        else:
            return JsonResponse({"error": f"Xatolik yuz berdi: {response.status_code}"}, status=400)

    return render(request, 'custom/save_books.html')

templates/book_app/book/book_list.html
{% extends 'base.html' %}
{% load static %}

{% block sidebar %}
{% include 'sidebar/student.html' %}
{% endblock sidebar %}

{% block topbar_header %}
{% include 'topbar_header/student.html' %}
{% endblock topbar_header %}


{% block custom_css %}
<!--Swiper slider css-->
<link href="{% static 'assets/libs/swiper/swiper-bundle.min.css' %}" rel="stylesheet" type="text/css">
{% endblock custom_css %}

{% block content %}
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0">Bosh sahifa</h4>

            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0 text-center">🔎 Kitob qidirish</h4>
            </div>
            <div class="card-body">
                <form method="GET">
                    <div class="row g-3">
                        <div class="col-xxl-4 col-sm-12">
                            <div class="search-box">
                                <input type="text" name="q" class="form-control search bg-light border-light"
                                       value="{{ query }}" autocomplete="off" placeholder="Kitob qidirish...">
                                <i class="ri-search-line search-icon"></i>
                            </div>
                        </div>
                        <!--end col-->
                        <div class="col-xxl-4 col-sm-4">
                            <!-- Select -->
                            <div class="input-group">
                                <select name="category" class="form-select bg-light">
                                    <option value="">Katalogni tanlang...</option>
                                    {% for category in categories %}
                                    <option value="{{ category.id }}" {% if category_id == category.id|stringformat:"s" %}selected{% endif %}>
                                        {{ category.name }}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <!--end col-->
                        <div class="col-xxl-2 col-sm-4">
                            <!-- Select -->
                            <div class="input-group">
                                <select name="language" class="form-select bg-light">
                                    <option value="">Tilni tanlang...</option>
                                    <option value="uz" {% if language == "uz" %}selected{% endif %}>O'zbekcha</option>
                                </select>
                            </div>
                        </div>
                        <!--end col-->

                        <div class="col-xxl-2 col-sm-4">
                            <button type="submit" class="btn btn-primary w-100">
                                <i class="ri-equalizer-fill me-1 align-bottom"></i> Filterlash
                            </button>
                        </div>
                        <!--end col-->
                    </div>
                    <!--end row-->
                </form>
            </div>
        </div>
    </div>
</div>


    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title mb-0 text-center">📙 Barcha kitoblar</h4>
                </div>
                <div class="card-body bg-light">
                    <div class="row">
                        {% for book in page_obj %}
                        <div class="col-xxl-3 col-sm-6 project-card">
                            <div class="card card-height-100">
                                <div class="card-body">
                                    <div class="d-flex flex-column h-100">
                                        <div class="d-flex">
                                            <div class="flex-grow-1">
                                                <p class="mb-4 text-success">⭐️ Yangi</p>
                                            </div>
                                        </div>
                                        <div class="d-flex mb-2">
                                            <div class="flex-shrink-0 me-3">
                                                <div class="avatar-sm">
                                                        <span class="avatar-title bg-warning-subtle rounded p-2">
                                                            {% if book.cover_image %}
                                                                <img src="{{ book.cover_image.url }}"
                                                                     alt="{{ book.title }}"
                                                                     class="img-fluid p-1">
                                                            {% else %}
                                                                <img src="{% static 'assets/images/new/default_cover.png' %}"
                                                                     alt="Kitob rasmi"
                                                                     class="img-fluid p-1">
                                                            {% endif %}
                                                        </span>
                                                </div>
                                            </div>
                                            <div class="flex-grow-1">
                                                <h5 class="mb-1 fs-14"><a
                                                        href="{% url 'book_app:student_book_detail' pk=book.id %}"
                                                        class="text-body">{{ book.title }}</a></h5>
                                                <p class="text-muted text-truncate-two-lines mb-3">{{ book.language }}</p>
                                            </div>
                                        </div>
                                        <div class="mt-auto">
                                            <div class="d-flex mb-2">
                                                <div class="flex-grow-1">
                                                    <div>{{ book.description|truncatewords:5 }}</div>
                                                </div>
                                                <div class="flex-shrink-0">
                                                    <div><i class="ri-list-check align-bottom me-1 text-muted"></i>
                                                        {{ book.page_count }} bet
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <!-- end card body -->
                                <div class="card-footer bg-transparent border-top-dashed py-2">
                                    <div class="d-flex align-items-center">
                                        <div class="flex-shrink-0">
                                            <div class="text-muted">
                                                <i class="ri-calendar-event-fill me-1 align-bottom"></i> {{ book.created_at }}
                                            </div>
                                        </div>

                                    </div>

                                </div>
                                <!-- end card footer -->
                            </div>
                            <!-- end card -->
                        </div>
                        <!-- end col -->
                        {% endfor %}

                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- Paginator -->
<div class="row g-0 text-center text-sm-start align-items-center mb-4">
    <div class="col-sm-6">
        <div>
            <p class="mb-sm-0 text-muted">
                Hozir sahifada <span class="fw-semibold">{{ page_obj.start_index }}</span> dan
                <span class="fw-semibold">{{ page_obj.end_index }}</span> gacha, jami
                <span class="fw-semibold text-decoration-underline">{{ page_obj.paginator.count }}</span> ta kitob
            </p>
        </div>
    </div>
    <div class="col-sm-6">
    <ul class="pagination pagination-separated justify-content-center justify-content-sm-end mb-sm-0">

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">«</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a href="#" class="page-link">«</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == 1 or num == page_obj.paginator.num_pages or num >= page_obj.number|add:"-1" and num <= page_obj.number|add:"1" %}
                {% if num == page_obj.number %}
                    <li class="page-item active">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                {% endif %}
            {% elif num == 2 or num == page_obj.paginator.num_pages|add:"-1" %}
                <li class="page-item disabled"><a href="#" class="page-link">...</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">»</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a href="#" class="page-link">»</a>
            </li>
        {% endif %}

    </ul>
</div>



</div>

</div>
<!-- container-fluid -->
{% endblock content %}

{% block custom_js %}
<!--Swiper slider js-->
<script src="{% static 'assets/libs/swiper/swiper-bundle.min.js' %}"></script>

<!-- swiper.init js -->
<script src="{% static 'assets/js/pages/swiper.init.js' %}"></script>
{% endblock custom_js %}